### ISSUE TITLE
Credentials invalid after update to 0.0.9

### ISSUE THREAD

**Issue by kopierschnitte** [PLCHome/ioBroker.growatt#1]
Hi!
Great adapter, thanks for your work.
I've noticed that the credentials needs to be entered again after updating from a build which stored them unencrypted. Otherwise, the login fails.
Maybe the adapter could identify unencrypted passwords and encrypt them accordingly...

**Comment by PLCHome** [comment]
First of all, thank you for the support and the trust that you install the beta.

I'm trying to get the adapter into the official repository. The merge was rejected because the password encryption was missing. The encryption was added in version 0.0.8. On my PI there was still a problem with decoding. For whatever reason, a flag was set there that the password does not have to be encrypted. This problem has been corrected in version 0.0.9.
The code for encrypting the passwords is given by the master of the ioBroker.

The key is now saved in the settings.
If I still manage to get the adapter into the ioBroker repository I don't want to change anything around this point, So this problem should no longer occur.

But I apologize again for the problems you had.

**I tested the adapter for my Growatt SPH 4000 (Interter with store). What kind of device do you use?**
The query is different for each of the device types. I have only tested the device types against the demo.


Should I ever manage to get the adapter into the repository of the ioBroker at some point. I would be happy to receive a test report on the test request in the iobroker board in order to add it to the stable versions.

**Comment by kopierschnitte** [comment]
Ahh, I understand. No need to apologize ... it took only a minute to figure it out ;-)
Of course I will do anything to support your efforts in getting this to the stable branch of ioBroker. I don't see any bugs at all!

I'm using the adapter with a **Growatt 1500-S Inverter** and a **ShineWIFI-S** module. The populated values are all correct and I get new values about once a minute.

There's indeed nothing more to wish ;-)

**Comment by PLCHome** [comment]
Do not update before 0.0.12

**Comment by PLCHome** [comment]
Would be nice if you could test the adapter so that I can get into the stable (default) with 0.0.12.
I need your comment for 0.0.12 here:

https://forum.iobroker.net/topic/36474/test-adapter-growatt-v0-0-12

**Comment by yunagear** [comment]
Servus PLC,

ich schreib mal auf deutsch:)
Kommentar hab ich schon geschrieben.
Aktuell fällt mir noch auf, dass der Adapter periodisch folgendes 
bringt:

growatt.0	2020-12-01 11:13:21.380	info	(13694) Terminated (NO_ERROR): 
Without reason
growatt.0	2020-12-01 11:13:21.379	info	(13694) terminating
growatt.0	2020-12-01 11:13:21.332	error	at process._tickCallback 
(internal/process/next_tick.js:68:7)
growatt.0	2020-12-01 11:13:21.332	error	at Promise 
(/opt/iobroker/node_modules/growatt/lib/growatt.js:883:23)
growatt.0	2020-12-01 11:13:21.332	error	(13694) TypeError: Cannot read 
property 'obj' of undefined
growatt.0	2020-12-01 11:13:21.332	error	(13694) unhandled promise 
rejection: Cannot read property 'obj' of undefined

Läuft aber sonst top.




Am 2020-11-30 21:25, schrieb PLCHome:

**Comment by PLCHome** [comment]
Aha, die Api liefert von Zeit zu Zeit kein Chart zurück.
Ich werde die API dahingehend anpassen.
