### ISSUE TITLE
current power reading is missing

### ISSUE THREAD

**Issue by UlliMUC** [PLCHome/ioBroker.growatt#5]
Hi,

first of all: thanks for this great adapter!

im looking for the reading of the current power. i only find growatt.0.xxxxxx.plantData.eTotal which represents the total power reading.

**Comment by PLCHome** [comment]
Please check again whether the value is displayed in the web interface in the status of the web interface (not mobile app). The adapter picks up exactly these values, Growatt had an error last because the value was not displayed in my mix. But it is available in the history, you can also check that once.

When making inquiries, please always specify the inverter type, whether it is a MIX or INV, this can also make a difference.

**Comment by UlliMUC** [comment]
Hi, wenn ok können wir gerne deutsch schreiben :)

Auf der Homepage sind alle Werte vorhanden. Aktuelle Leistung, Tagesleistung und Gesamtleistung.

Im Iobroker sehe ich diese auch im Admin-Panel unter Instanzen -> Objekte verwalten. Diese fehlen jedoch in den Objekten, die ich zur Darstellung nutzen kann. Muss man die Objekte/Variablen erst noch umwandeln? Ich beschäftige mich noch nicht so lange mit dem iobroker.

**Comment by PLCHome** [comment]
Schaum mal bitte nach, ob es eine Warnmeldung kommt, wenn du den Adapter durchstartest.
Vielleicht gibt es 2 Objekte: growatt.0.xxx.plantData.eTotal, growatt.0.xxx.plantData.etotal

Growatt hat schon öfters Groß- und Kleinschreibung geändert. Das sind dann 2 Objekte aktualisiert wird aber nur eines, deswegen die Warnung beim Start, es muss dann eines gelöscht werden.

**Comment by UlliMUC** [comment]
Wie peinlich - ein Neustart des Adapters hat das Problem beseitigt. Danke :)

**Comment by PLCHome** [comment]
You are welcome
